cicd 수정

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -53,9 +53,24 @@ jobs:
           DOCKER_HUB_REPOSITORY: ${{ secrets.DOCKER_HUB_REPOSITORY }}
         run: |
           echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
-          BASE_REF="${{ github.base_ref }}"
-          DOCKER_TAG=$(basename $BASE_REF)
-          echo "Docker tag set to: $DOCKER_TAG"
+          if [ "${{ github.event_name }}" = "push" ]; then
+            if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
+              DOCKER_TAG="develop"
+            elif [ "${{ github.ref }}" = "refs/heads/main" ]; then
+              DOCKER_TAG="main"
+            fi
+          elif [ "${{ github.event_name }}" = "pull_request" ]; then
+            if [ "${{ github.base_ref }}" = "develop" ]; then
+              DOCKER_TAG="develop"
+            elif [ "${{ github.base_ref }}" = "main" ]; then
+              DOCKER_TAG="main"
+            fi
+          fi
+
+          if [ -z "$DOCKER_TAG" ]; then
+          echo "Error: DOCKER_TAG is not set"
+            exit 1
+          fi          
   
           docker build \
             --build-arg DATABASE_URL="$DATABASE_URL" \
